// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43X8OkALAQf6iWVXEKcLWma7NAsUkS_Q',
    appId: '1:1022135089366:web:51be155fed8ca473977177',
    messagingSenderId: '1022135089366',
    projectId: 'evcildostum-f2326',
    authDomain: 'evcildostum-f2326.firebaseapp.com',
    storageBucket: 'evcildostum-f2326.appspot.com',
    measurementId: 'G-D2T59ENDKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLZSiK3d9ats5a_vXnNnhzWUF7eG4yjM',
    appId: '1:1022135089366:android:5343a4b1067760f4977177',
    messagingSenderId: '1022135089366',
    projectId: 'evcildostum-f2326',
    storageBucket: 'evcildostum-f2326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYbezhCYF8aVr5B7cPMT1rrzjov6Te-aY',
    appId: '1:1022135089366:ios:339b5775cde4e8ff977177',
    messagingSenderId: '1022135089366',
    projectId: 'evcildostum-f2326',
    storageBucket: 'evcildostum-f2326.appspot.com',
    iosBundleId: 'com.example.evcildostum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYbezhCYF8aVr5B7cPMT1rrzjov6Te-aY',
    appId: '1:1022135089366:ios:2d216c3c0a072f5a977177',
    messagingSenderId: '1022135089366',
    projectId: 'evcildostum-f2326',
    storageBucket: 'evcildostum-f2326.appspot.com',
    iosBundleId: 'com.example.evcildostum.RunnerTests',
  );
}
